image:
  repository: ghcr.io/hyperledger/firefly-signer
  pullPolicy: IfNotPresent
  tag: "v1.1.22"

backend:
  url: http://fabconnect.default.svc.cluster.local:3000
  chainId: 1337

signer:
  enabled: true

service:
  type: ClusterIP
  port: 8545
