apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: chaincode-install-pm3org-peer0-pm3roleauth-1
  namespace: pm3org-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: chaincode-install-pm3org-peer0-pm3roleauth-1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/fabric-chaincode-install
  values:
    metadata:
      namespace: pm3org-net
      network:
        version: 2.5.4
      images:
        fabrictools: ghcr.io/hyperledger/bevel-fabric-tools:2.5.4
        alpineutils: ghcr.io/hyperledger/bevel-alpine:latest

    peer:
      name: peer0
      address: peer0.pm3org-net:7051
      localmspid: pm3orgMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://192.168.49.1:8200
      authpath: localpm3org
      adminsecretprefix: secretsv2/data/localpm3org/users/admin
      secretgitprivatekey: secretsv2/data/localpm3org/credentials/pm3org-net/git
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: ""
      tls: false
    chaincode:
      builder: hyperledger/fabric-ccenv:2.5.4
      name: pm3roleauth
      version: 1
      lang: node
      maindirectory: .
      repository:
        hostname: "github.com"
        git_username: "Fraktal-PM3"
        url: github.com/Fraktal-PM3/fraktal.git
        branch: main
        path: chaincodes/roleAuth/
      endorsementpolicies:  ''
