apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fabconnect.fullname" . }}-ccp
  labels:
    app: {{ include "fabconnect.name" . }}
data:
  ccp.yaml: |
    certificateAuthorities:
      {{ .Values.organizationName }}:
        tlsCACerts:
          path: /etc/firefly/organizations/peerOrganizations/{{ .Values.organizationName }}/msp/tlscacerts/ca.crt
        url: {{ .Values.caUrl }}
        registrar:
          enrollId: {{ .Values.enrollId }}
          enrollSecret: {{ .Values.enrollSecret }}
    channels:
      {{ .Values.channelName }}:
        orderers:
          - {{ .Values.organizationName }}_orderer
        peers:
          {{ .Values.organizationName }}_peer:
            chaincodeQuery: true
            endorsingPeer: true
            eventSource: true
            ledgerQuery: true
    client:
      BCCSP:
        security:
          default:
            provider: SW
          enabled: true
          hashAlgorithm: SHA2
          level: 256
          softVerify: true
      credentialStore:
        cryptoStore:
          path: /etc/firefly/organizations/peerOrganizations/{{ .Values.organizationName }}/msp
        path: /etc/firefly/organizations/peerOrganizations/{{ .Values.organizationName }}/msp
      cryptoconfig:
        path: /etc/firefly/organizations/peerOrganizations/{{ .Values.organizationName }}/msp
      logging:
        level: info
      organization: {{ .Values.organizationName }}
      tlsCerts:
        client:
          cert:
            path: /etc/firefly/organizations/peerOrganizations/{{ .Values.organizationName }}/users/Admin@{{ .Values.organizationName }}/msp/signcerts/cert.pem
          key:
            path: /etc/firefly/organizations/peerOrganizations/{{ .Values.organizationName }}/users/Admin@{{ .Values.organizationName }}/msp/keystore/key.pem
    orderers:
      {{ .Values.organizationName }}_orderer:
        tlsCACerts:
          path: /etc/firefly/organizations/ordererOrganizations/pm3org/orderers/orderer0.pm3org/tls/tlscacerts/tls-ca-orderer.pem
        url: {{ .Values.ordererUrl }}
    organizations:
      {{ .Values.organizationName }}:
        certificateAuthorities:
          - {{ .Values.organizationName }}
        cryptoPath: /tmp/msp
        mspid: {{ .Values.organizationMspId }}
        peers:
          - {{ .Values.organizationName }}_peer
    peers:
      {{ .Values.organizationName }}_peer:
        tlsCACerts:
          path: /etc/firefly/organizations/peerOrganizations/{{ .Values.organizationName }}/peers/peer0.{{ .Values.organizationName }}/tls/tlscacerts/tls-ca-{{ .Values.organizationName }}.pem
        url: {{ .Values.peerUrl }}
    version: 1.1.0
