apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fabconnect.fullname" . }}-config
  labels:
    app: {{ include "fabconnect.name" . }}
data:
  fabconnect.yaml: |
    maxinflight: {{ .Values.config.maxInFlight }}
    maxtxwaittime: {{ .Values.config.maxTXWaitTime }}
    sendconcurrency: {{ .Values.config.sendConcurrency }}
    receipts:
      maxdocs: 1000
      querylimit: 100
      retryinitialdelay: 5
      retrytimeout: 30
      leveldb:
        path: /fabconnect/receipts
    events:
      webhooksAllowPrivateIPs: {{ .Values.config.webhooksAllowPrivateIPs }}
      leveldb:
        path: /fabconnect/events
    http:
      port: {{ .Values.config.port }}
    rpc:
      configpath: /fabconnect/ccp.yaml
