apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fabconnect.fullname" . }}
  labels:
    app: {{ include "fabconnect.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "fabconnect.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "fabconnect.name" . }}
    spec:
      containers:
        - name: fabconnect
          image: "{{ .Values.image.repository }}@{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["-f", "/fabconnect/fabconnect.yaml"]
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.healthcheck.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthcheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.healthcheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthcheck.periodSeconds }}
            timeoutSeconds: {{ .Values.healthcheck.timeoutSeconds }}
            successThreshold: {{ .Values.healthcheck.successThreshold }}
            failureThreshold: {{ .Values.healthcheck.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthcheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.healthcheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthcheck.periodSeconds }}
            timeoutSeconds: {{ .Values.healthcheck.timeoutSeconds }}
            successThreshold: {{ .Values.healthcheck.successThreshold }}
            failureThreshold: {{ .Values.healthcheck.failureThreshold }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /fabconnect/fabconnect.yaml
              subPath: fabconnect.yaml
              readOnly: true
            - name: ccp
              mountPath: /fabconnect/ccp.yaml
              subPath: ccp.yaml
              readOnly: true
            - name: msp
              mountPath: /etc/firefly/organizations
              readOnly: true
            - name: receipts
              mountPath: /fabconnect/receipts
            - name: events
              mountPath: /fabconnect/events
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "fabconnect.fullname" . }}-config
        - name: ccp
          configMap:
            name: {{ include "fabconnect.fullname" . }}-ccp
        - name: msp
          secret:
            secretName: {{ .Values.mspSecret }}
        - name: receipts
          emptyDir: {}
        - name: events
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
